# Generated by Django 3.2.7 on 2022-04-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendees',
            options={'verbose_name_plural': 'Attendees'},
        ),
    ]
